name: MKTAC
favicon: null
layout_spectrum: 0.35646
typography_spectrum: 0.8507425205316395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a7a7a7'
    - '#d0d0d0'
    - '#575757'
    - '#d87d3f'
  brandStrength: 0.6466506943106651
  lightness: 0.23443050286732614
  saturation: 0.7511577743571252
  rhythmicContrast: 0.7271502166986465
purpose: []
