name: MKTAC
favicon: null
layout_spectrum: 0.3643010628875345
typography_spectrum: 0.8507425205316395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6466506943106651
  lightness: 0.23443050286732614
  saturation: 0.7511577743571252
  rhythmicContrast: 0.7271502166986465
purpose: []
